// Auto-generated by scripts/sync-extensions.ts
// Do not edit manually.

macro_rules! configure_app {
    ($builder:expr) => {
        $builder
            .invoke_handler(tauri::generate_handler![
        crate::extensions::shortcut::is_app_active,
        crate::extensions::shortcut::hide_window,
        crate::extensions::shortcut::get_selected_text_cached,
        crate::extensions::shortcut::register_global_shortcut,
        crate::extensions::screenshot::capture_screen,
        crate::extensions::screenshot::ocr_image,
        crate::extensions::screenshot::save_screenshot,
        crate::extensions::screenshot::copy_screenshot_to_clipboard,
        crate::extensions::screenshot::enter_screenshot_mode,
        crate::extensions::screenshot::show_screenshot_window,
        crate::extensions::screenshot::exit_screenshot_mode,
        crate::extensions::screenshot::open_ocr_window,
        crate::extensions::screenshot::pin_image,
        crate::extensions::screenshot::set_pin_window_opacity,
        crate::extensions::screenshot::open_module_panel,
        crate::extensions::chat::chat_stream,
        crate::extensions::translate::get_selected_text,
        crate::extensions::translate::translate_youdao,
        crate::extensions::translate::translate_ai,
        crate::extensions::translate::translate_ai_stream,
        crate::extensions::search::search_apps,
        crate::extensions::search::search_files,
        crate::extensions::search::get_recent_apps,
        crate::extensions::search::launch_app,
        crate::extensions::search::reveal_in_finder,
        crate::extensions::search::score_items,
        crate::extensions::window::set_main_window_size,
        crate::extensions::window::get_home_dir,
        crate::extensions::window::pick_directory,
        crate::extensions::finder_ext::set_finder_ext_enabled,
        crate::extensions::finder_ext::quit_app,
        crate::extensions::finder_ext::open_extensions_prefs,
        crate::extensions::ip::fetch_ip_info,
        crate::extensions::awake::toggle_awake,
        crate::extensions::awake::is_awake_enabled,
        crate::extensions::clipboard::get_clipboard_history,
        crate::extensions::clipboard::clear_clipboard_history,
        crate::extensions::clipboard::toggle_clipboard_favorite,
        crate::extensions::clipboard::paste_clipboard_item,
            ])
        .plugin(crate::extensions::shortcut::init())
        .plugin(crate::extensions::screenshot::init())
        .plugin(crate::extensions::chat::init())
        .plugin(crate::extensions::translate::init())
        .plugin(crate::extensions::search::init())
        .plugin(crate::extensions::window::init())
        .plugin(crate::extensions::finder_ext::init())
        .plugin(crate::extensions::ip::init())
        .plugin(crate::extensions::awake::init())
        .plugin(crate::extensions::clipboard::init())
    };
}
pub(crate) use configure_app;

#[path = "../../../extensions/shortcut/backend/mod.rs"]
pub mod shortcut;
#[path = "../../../extensions/screenshot/backend/mod.rs"]
pub mod screenshot;
#[path = "../../../extensions/chat/backend/mod.rs"]
pub mod chat;
#[path = "../../../extensions/translate/backend/mod.rs"]
pub mod translate;
#[path = "../../../extensions/search/backend/mod.rs"]
pub mod search;
#[path = "../../../extensions/window/backend/mod.rs"]
pub mod window;
#[path = "../../../extensions/finder-ext/backend/mod.rs"]
pub mod finder_ext;
#[path = "../../../extensions/ip/backend/mod.rs"]
pub mod ip;
#[path = "../../../extensions/awake/backend/mod.rs"]
pub mod awake;
#[path = "../../../extensions/clipboard/backend/mod.rs"]
pub mod clipboard;
pub mod registry;
