#!/usr/bin/env bun
import { readdir, readFile, writeFile, stat, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

const ROOT = process.cwd()
const EXTENSIONS_DIR = join(ROOT, 'extensions')
const BACKEND_EXT_DIR = join(ROOT, 'src-tauri', 'src', 'extensions')
const COMMANDS_DIR = join(ROOT, 'src-tauri', 'src', 'commands')

const IS_CHECK_MODE = process.argv.includes('--check')

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function scanExtensions(): Promise<string[]> {
  if (!(await pathExists(EXTENSIONS_DIR))) return []
  const items = await readdir(EXTENSIONS_DIR, { withFileTypes: true })
  return items
    .filter(d => d.isDirectory() && !d.name.startsWith('.') && d.name !== 'README.md')
    .map(d => d.name)
    .sort()
}

// 匹配 #[tauri::command] 及后续可能的 #[cfg_attr(...)]，然后 pub (async)? fn name(
const COMMAND_REGEX = /#\[tauri::command\]\s*(?:#\[.*?\]\s*)*pub\s+(?:async\s+)?fn\s+(\w+)/g

// 匹配 pub fn init(  而非 init_something(
const INIT_REGEX = /^pub\s+fn\s+init\s*\(/m

function extractCommands(content: string): string[] {
  const commands: string[] = []
  let match: RegExpExecArray | null
  while ((match = COMMAND_REGEX.exec(content)) !== null) {
    commands.push(match[1])
  }
  return commands
}

function hasInit(content: string): boolean {
  return INIT_REGEX.test(content)
}

interface ModuleMeta {
  module: string
  commands: string[]
  hasInit: boolean
  source: 'built-in' | 'extension'
  backendPath?: string  // relative path from src-tauri/src/extensions/ to mod.rs
}

async function scanBuiltInCommands(): Promise<ModuleMeta[]> {
  const results: ModuleMeta[] = []
  if (!(await pathExists(COMMANDS_DIR))) return results

  const files = await readdir(COMMANDS_DIR)

  for (const file of files) {
    if (!file.endsWith('.rs') || file === 'mod.rs') continue
    const module = file.replace('.rs', '')
    const content = await readFile(join(COMMANDS_DIR, file), 'utf-8')
    const commands = extractCommands(content)
    const init = hasInit(content)
    if (commands.length > 0 || init) {
      results.push({ module, commands, hasInit: init, source: 'built-in' })
    }
  }

  return results
}

async function scanExtensionBackends(): Promise<ModuleMeta[]> {
  const results: ModuleMeta[] = []
  if (!(await pathExists(EXTENSIONS_DIR))) return results

  const dirs = await readdir(EXTENSIONS_DIR, { withFileTypes: true })
  for (const dir of dirs.filter(d => d.isDirectory())) {
    const modFile = join(EXTENSIONS_DIR, dir.name, 'backend', 'mod.rs')
    if (!(await pathExists(modFile))) continue

    const content = await readFile(modFile, 'utf-8')
    const commands = extractCommands(content)
    const init = hasInit(content)
    if (commands.length > 0 || init) {
      results.push({
        module: dir.name,
        commands,
        hasInit: init,
        source: 'extension',
        backendPath: `../../../extensions/${dir.name}/backend/mod.rs`
      })
    }
  }

  return results
}

function buildRegistryContent(allModules: ModuleMeta[]): { modContent: string; registryContent: string } {
  const extModules = allModules.filter(m => m.source === 'extension')

  // mod declarations with #[path] for extension backends
  const rustModuleName = (name: string) => name.replace(/-/g, '_')

  const modLines: string[] = []
  for (const m of extModules) {
    if (m.backendPath) {
      modLines.push(`#[path = "${m.backendPath}"]`)
      modLines.push(`pub mod ${rustModuleName(m.module)};`)
    }
  }

  const commandPaths: string[] = []
  for (const m of allModules) {
    const prefix = m.source === 'built-in' ? 'crate::commands' : 'crate::extensions'
    const modName = rustModuleName(m.module)
    for (const cmd of m.commands) {
      commandPaths.push(`        ${prefix}::${modName}::${cmd},`)
    }
  }

  const initLines: string[] = []
  for (const m of allModules) {
    if (m.hasInit) {
      const prefix = m.source === 'built-in' ? 'crate::commands' : 'crate::extensions'
      const modName = rustModuleName(m.module)
      initLines.push(`        .plugin(${prefix}::${modName}::init())`)
    }
  }

  // 用 macro_rules! 在调用点展开，保留 lib.rs 顶层的具体类型推断
  const modContent = [
    `// Auto-generated by scripts/sync-extensions.ts`,
    `// Do not edit manually.`,
    ``,
    `macro_rules! configure_app {`,
    `    ($builder:expr) => {`,
    `        $builder`,
    `            .invoke_handler(tauri::generate_handler![`,
    ...commandPaths,
    `            ])`,
    ...initLines,
    `    };`,
    `}`,
    `pub(crate) use configure_app;`,
    ``,
    ...modLines,
    `pub mod registry;`,
    ``,
  ].join('\n')

  // registry.rs 保留为占位（未来可放扩展的辅助函数）
  const registryContent = [
    `// Auto-generated by scripts/sync-extensions.ts`,
    `// Do not edit manually.`,
    ``,
    `// 命令注册通过 extensions/mod.rs 中的 configure_app! 宏完成`,
    ``,
  ].join('\n')

  return { modContent, registryContent }
}

async function generateRegistry(allModules: ModuleMeta[]) {
  const { modContent, registryContent } = buildRegistryContent(allModules)

  await mkdir(BACKEND_EXT_DIR, { recursive: true })
  await writeFile(join(BACKEND_EXT_DIR, 'mod.rs'), modContent)
  await writeFile(join(BACKEND_EXT_DIR, 'registry.rs'), registryContent)
}

async function checkRegistry(allModules: ModuleMeta[]): Promise<boolean> {
  const { modContent, registryContent } = buildRegistryContent(allModules)

  const modPath = join(BACKEND_EXT_DIR, 'mod.rs')
  const registryPath = join(BACKEND_EXT_DIR, 'registry.rs')

  let ok = true

  if (await pathExists(modPath)) {
    const existing = await readFile(modPath, 'utf-8')
    if (existing !== modContent) {
      console.error(`[sync-extensions] CHECK FAILED: ${modPath} is out of date.`)
      ok = false
    }
  } else {
    console.error(`[sync-extensions] CHECK FAILED: ${modPath} does not exist.`)
    ok = false
  }

  if (await pathExists(registryPath)) {
    const existing = await readFile(registryPath, 'utf-8')
    if (existing !== registryContent) {
      console.error(`[sync-extensions] CHECK FAILED: ${registryPath} is out of date.`)
      ok = false
    }
  } else {
    console.error(`[sync-extensions] CHECK FAILED: ${registryPath} does not exist.`)
    ok = false
  }

  return ok
}

async function main() {
  console.log('[sync-extensions] Scanning extensions...')

  const extNames = await scanExtensions()
  console.log(`[sync-extensions] Found ${extNames.length} extension(s): ${extNames.join(', ') || 'none'}`)

  const builtIns = await scanBuiltInCommands()
  const extBackends = await scanExtensionBackends()
  const allModules = [...builtIns, ...extBackends]

  if (IS_CHECK_MODE) {
    const ok = await checkRegistry(allModules)
    if (!ok) {
      console.error('[sync-extensions] Run `bun run sync:extensions` to regenerate.')
      process.exit(1)
    }
    console.log('[sync-extensions] Check passed.')
    return
  }

  await generateRegistry(allModules)

  const totalCommands = allModules.reduce((sum, m) => sum + m.commands.length, 0)
  const totalPlugins = allModules.filter(m => m.hasInit).length

  console.log('[sync-extensions] Done.')
  console.log(`  Modules:  ${builtIns.length} built-in + ${extBackends.length} extension`)
  console.log(`  Commands: ${totalCommands}`)
  console.log(`  Plugins:  ${totalPlugins}`)
}

main().catch(e => {
  console.error('[sync-extensions] Error:', e)
  process.exit(1)
})
