#!/usr/bin/env bun
// 扫描 extensions/*/native/mod.rs 的 `pub fn init()` 签名，生成 extensions.rs：
//   - `configure_app!` 宏：仅 `.plugin()` 链（零 generate_handler!）
//   - `#[path]` mod 声明
// 扩展命令在各 init() 局部注册；框架命令（permission/shortcut/window）在 lib.rs 手写。
// 详见 docs/REFACTOR-V2.md §2.8。
//
// 另含 windowViews 漂移校验（v1.5 A4）：声明 windowViews 槽的扩展，每个 key 必须在
// tauri.conf.json 的 windows[].label 中存在；以 `-` 或 `*` 结尾的 key 视为动态窗口前缀
// （如 `pin-` 匹配运行时创建的 `pin-<id>`），跳过精确匹配。
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const EXT_DIR = join(ROOT, 'extensions')
const OUT_FILE = join(ROOT, 'src-tauri', 'src', 'extensions.rs')
const CONF_FILE = join(ROOT, 'src-tauri', 'tauri.conf.json')

const INIT_REGEX = /^pub\s+fn\s+init\s*\(/m
const rustName = (id: string) => id.replace(/-/g, '_')

function scanInitExtensions(): string[] {
  const ids: string[] = []
  for (const dir of readdirSync(EXT_DIR)) {
    const modPath = join(EXT_DIR, dir, 'native', 'mod.rs')
    if (!existsSync(modPath)) continue // 纯 TS 扩展无 native
    const src = readFileSync(modPath, 'utf8')
    if (INIT_REGEX.test(src)) ids.push(dir)
  }
  return ids.sort()
}

function buildExtensionsRs(ids: string[]): string {
  const pluginChain = ids
    .map((id) => `        .plugin(crate::extensions::${rustName(id)}::init())`)
    .join('\n')
  const modDecls = ids
    .map((id) => `#[path = "../../extensions/${id}/native/mod.rs"]\npub mod ${rustName(id)};`)
    .join('\n\n')
  return `// AUTO-GENERATED by scripts/sync-extensions.ts. DO NOT EDIT.
// 仅含扩展 .plugin() 链 + mod 声明；零 generate_handler!（见 §2.8）。

macro_rules! configure_app {
    ($builder:expr) => {
        $builder
${pluginChain}
    };
}
pub(crate) use configure_app;

${modDecls}
`
}

const ids = scanInitExtensions()
const content = buildExtensionsRs(ids)

// windowViews 漂移校验（v1.5 A4）：始终运行（sync 与 --check 模式均校验）
const wvError = checkWindowViews()
if (wvError) {
  console.error(`[sync-extensions] CHECK FAILED: ${wvError}`)
  process.exit(1)
}

if (process.argv.includes('--check')) {
  const existing = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : ''
  if (existing !== content) {
    console.error(
      '[sync-extensions] CHECK FAILED: extensions.rs is out of date. Run `bun run sync:extensions`.',
    )
    process.exit(1)
  }
  console.log(`[sync-extensions] Check passed (${ids.length} extensions).`)
} else {
  writeFileSync(OUT_FILE, content)
  console.log(`[sync-extensions] Synced ${ids.length} extensions: ${ids.join(', ')}`)
}

/** 提取对象字面量块（从 `windowViews:` 后的 `{` 起到匹配的 `}`），返回块内文本。 */
function extractBlock(src: string, key: string): string | null {
  const idx = src.indexOf(`${key}:`)
  if (idx === -1) return null
  let i = idx + key.length
  while (i < src.length && src[i] !== '{') i++
  if (src[i] !== '{') return null
  let depth = 0
  const start = i + 1
  for (; i < src.length; i++) {
    const c = src[i]
    if (c === '{') depth++
    else if (c === '}') {
      depth--
      if (depth === 0) return src.slice(start, i)
    }
  }
  return null
}

/** 从 windowViews 块提取所有 key（兼容 bare / 单引号 / 双引号）。 */
function extractWindowViewKeys(block: string): string[] {
  const keys: string[] = []
  const re = /(?:'([^']+)'|"([^"]+)"|([A-Za-z_$][\w$]*))\s*:/g
  let m: RegExpExecArray | null
  while ((m = re.exec(block)) !== null) {
    keys.push(m[1] ?? m[2] ?? m[3])
  }
  return keys
}

/** windowViews 漂移校验：返回错误消息（null = 通过）。 */
function checkWindowViews(): string | null {
  if (!existsSync(CONF_FILE)) return null // 配置缺失时不阻塞（由其他校验兜底）
  const conf = JSON.parse(readFileSync(CONF_FILE, 'utf8'))
  const labels = new Set<string>((conf?.app?.windows ?? []).map((w: { label: string }) => w.label))
  if (labels.size === 0) return null

  const violations: string[] = []
  for (const dir of readdirSync(EXT_DIR)) {
    const indexPath = join(EXT_DIR, dir, 'index.ts')
    if (!existsSync(indexPath)) continue
    const src = readFileSync(indexPath, 'utf8')
    const block = extractBlock(src, 'windowViews')
    if (!block) continue
    for (const key of extractWindowViewKeys(block)) {
      // 以 `-` 或 `*` 结尾 = 动态窗口前缀（如 `pin-`/`pin-*`），跳过精确匹配
      if (key.endsWith('-') || key.endsWith('*')) continue
      if (!labels.has(key)) {
        violations.push(
          `extensions/${dir}/index.ts windowViews key '${key}' 不在 tauri.conf.json windows[].label 中`,
        )
      }
    }
  }
  if (violations.length === 0) return null
  return `windowViews 漂移（v1.5 A4）：\n  ${violations.join('\n  ')}`
}
