#!/usr/bin/env bun
// 扫描 extensions/*/native/mod.rs 的 `pub fn init()` 签名，生成 extensions.rs：
//   - `configure_app!` 宏：仅 `.plugin()` 链（零 generate_handler!）
//   - `#[path]` mod 声明
// 扩展命令在各 init() 局部注册；框架命令（permission/shortcut/window）在 lib.rs 手写。
// 详见 docs/REFACTOR-V2.md §2.8。
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const EXT_DIR = join(ROOT, 'extensions')
const OUT_FILE = join(ROOT, 'src-tauri', 'src', 'extensions.rs')

const INIT_REGEX = /^pub\s+fn\s+init\s*\(/m
const rustName = (id: string) => id.replace(/-/g, '_')

function scanInitExtensions(): string[] {
  const ids: string[] = []
  for (const dir of readdirSync(EXT_DIR)) {
    const modPath = join(EXT_DIR, dir, 'native', 'mod.rs')
    if (!existsSync(modPath)) continue // 纯 TS 扩展无 native
    const src = readFileSync(modPath, 'utf8')
    if (INIT_REGEX.test(src)) ids.push(dir)
  }
  return ids.sort()
}

function buildExtensionsRs(ids: string[]): string {
  const pluginChain = ids
    .map((id) => `        .plugin(crate::extensions::${rustName(id)}::init())`)
    .join('\n')
  const modDecls = ids
    .map((id) => `#[path = "../../extensions/${id}/native/mod.rs"]\npub mod ${rustName(id)};`)
    .join('\n\n')
  return `// AUTO-GENERATED by scripts/sync-extensions.ts. DO NOT EDIT.
// 仅含扩展 .plugin() 链 + mod 声明；零 generate_handler!（见 §2.8）。

macro_rules! configure_app {
    ($builder:expr) => {
        $builder
${pluginChain}
    };
}
pub(crate) use configure_app;

${modDecls}
`
}

const ids = scanInitExtensions()
const content = buildExtensionsRs(ids)

if (process.argv.includes('--check')) {
  const existing = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : ''
  if (existing !== content) {
    console.error(
      '[sync-extensions] CHECK FAILED: extensions.rs is out of date. Run `bun run sync:extensions`.',
    )
    process.exit(1)
  }
  console.log(`[sync-extensions] Check passed (${ids.length} extensions).`)
} else {
  writeFileSync(OUT_FILE, content)
  console.log(`[sync-extensions] Synced ${ids.length} extensions: ${ids.join(', ')}`)
}
