[extension]
id = "base64"
name = "Base64 编解码"
version = "1.0.0"
description = "Base64 编码与解码"
author = "Voidnix"
icon = "i-ri-code-s-slash-line"
keywords = ["base64", "encode", "decode", "编码", "解码"]
voidnix_api = "^1"

[entry]
main = "index.js"

[ui]
preferred_view = "list"
search_placeholder = "输入文本"
