// AUTO-GENERATED by scripts/sync-extensions.ts. DO NOT EDIT.
// configure_app! 含全局 invoke_handler（框架 + 扩展命令）。
// register_all 注册全部 native Extension trait 实现（bootstrap 生命周期）。
// 扩展命令全局注册（裸名 invoke）；扩展无 plugin 空壳（命令走 generate_handler!，
// State 经 Extension trait setup 管理）。

macro_rules! configure_app {
    ($builder:expr) => {
        $builder.invoke_handler(tauri::generate_handler![
            crate::http::http_get,
            crate::runtime::autostart::disable_autostart,
            crate::runtime::autostart::enable_autostart,
            crate::runtime::autostart::is_autostart_enabled,
            crate::runtime::pasteboard::pasteboard_paste_text,
            crate::runtime::pasteboard::pasteboard_write_text,
            crate::runtime::permission::check_accessibility_permission,
            crate::runtime::permission::check_full_disk_access_permission,
            crate::runtime::permission::check_screen_recording_permission,
            crate::runtime::permission::open_privacy_settings,
            crate::runtime::permission::request_accessibility_permission,
            crate::runtime::shortcut::hide_window,
            crate::runtime::shortcut::is_app_active,
            crate::runtime::shortcut::register_global_shortcut,
            crate::runtime::shortcut::start_shortcut_recording,
            crate::runtime::shortcut::stop_shortcut_recording,
            crate::runtime::speech::speak_text,
            crate::runtime::speech::stop_speech,
            crate::runtime::test::is_self_test_mode,
            crate::runtime::test::self_test_diag,
            crate::runtime::window::get_cached_appearance,
            crate::runtime::window::get_home_dir,
            crate::runtime::window::pick_directory,
            crate::runtime::window::pick_files,
            crate::runtime::window::quit_app,
            crate::runtime::window::set_main_frame,
            crate::runtime::window::set_window_appearance,
            crate::runtime::window::show_window,
            crate::extensions::agent::agent_abort,
            crate::extensions::agent::agent_run,
            crate::extensions::ai_providers::ai_providers_env_snapshot,
            crate::extensions::ai_providers::ai_providers_export,
            crate::extensions::ai_providers::ai_providers_export_dir,
            crate::extensions::ai_providers::usage::deepseek::ai_providers_deepseek_balance,
            crate::extensions::ai_providers::usage::zhipu::ai_providers_zhipu_quota,
            crate::extensions::awake::is_awake_enabled,
            crate::extensions::awake::set_awake_display_mode,
            crate::extensions::awake::set_awake_enabled,
            crate::extensions::clean_mode::is_clean_mode_enabled,
            crate::extensions::clean_mode::set_clean_mode_enabled,
            crate::extensions::clipboard::commands::clear_clipboard_history,
            crate::extensions::clipboard::commands::delete_clipboard_items,
            crate::extensions::clipboard::commands::get_clipboard_history,
            crate::extensions::clipboard::commands::get_clipboard_image,
            crate::extensions::clipboard::commands::get_clipboard_text,
            crate::extensions::clipboard::commands::paste_clipboard_item,
            crate::extensions::clipboard::commands::paste_clipboard_items,
            crate::extensions::clipboard::commands::toggle_clipboard_favorite,
            crate::extensions::clipboard::commands::update_clipboard_text,
            crate::extensions::clipboard::set_clipboard_max_days,
            crate::extensions::finder_ext::finder_run_action,
            crate::extensions::finder_ext::finder_selected_paths,
            crate::extensions::homebrew::brew_info,
            crate::extensions::homebrew::brew_run,
            crate::extensions::homebrew::brew_run_state,
            crate::extensions::homebrew::brew_services,
            crate::extensions::homebrew::brew_status,
            crate::extensions::image::image_copy_to_clipboard,
            crate::extensions::image::image_read_preview,
            crate::extensions::image::image_remove_bg,
            crate::extensions::image::image_save_result,
            crate::extensions::image::image_stitch,
            crate::extensions::proxy::is_proxy_enabled,
            crate::extensions::proxy::proxy_check_update,
            crate::extensions::proxy::proxy_connections_stream,
            crate::extensions::proxy::proxy_core_status,
            crate::extensions::proxy::proxy_ensure_core,
            crate::extensions::proxy::proxy_get_proxies,
            crate::extensions::proxy::proxy_get_rules,
            crate::extensions::proxy::proxy_logs_stream,
            crate::extensions::proxy::proxy_reconnect,
            crate::extensions::proxy::proxy_remove_subscription,
            crate::extensions::proxy::proxy_select_proxy,
            crate::extensions::proxy::proxy_set_active_subscription,
            crate::extensions::proxy::proxy_set_mode,
            crate::extensions::proxy::proxy_stop_stream,
            crate::extensions::proxy::proxy_test_group_delay_stream,
            crate::extensions::proxy::proxy_traffic_stream,
            crate::extensions::proxy::proxy_update_core,
            crate::extensions::proxy::proxy_update_subscription,
            crate::extensions::proxy::set_proxy_enabled,
            crate::extensions::screenshot::ocr::copy_screenshot_to_clipboard,
            crate::extensions::screenshot::ocr::detect_text_regions,
            crate::extensions::screenshot::ocr::ocr_image,
            crate::extensions::screenshot::ocr::save_screenshot,
            crate::extensions::screenshot::open_extension_subview,
            crate::extensions::screenshot::pin::pin_global_mouse,
            crate::extensions::screenshot::pin::pin_image,
            crate::extensions::screenshot::pin::restore_pin_focus,
            crate::extensions::screenshot::pin::scale_pin_window,
            crate::extensions::screenshot::pin::set_pin_window_opacity,
            crate::extensions::screenshot::scroll_capture::copy_scroll_result_to_clipboard,
            crate::extensions::screenshot::scroll_capture::enter_scroll_capture,
            crate::extensions::screenshot::scroll_capture::exit_scroll_capture,
            crate::extensions::screenshot::scroll_capture::finish_scroll_capture,
            crate::extensions::screenshot::scroll_capture::save_scroll_result,
            crate::extensions::screenshot::scroll_capture::set_scroll_toolbar_rect,
            crate::extensions::screenshot::session::exit_screenshot_mode,
            crate::extensions::screenshot::session::read_picker_image,
            crate::extensions::screenshot::session::save_last_selection,
            crate::extensions::screenshot::session::screenshot_overlay_ready,
            crate::extensions::search::commands::get_app_icons,
            crate::extensions::search::commands::get_path_metadata,
            crate::extensions::search::commands::launch_app,
            crate::extensions::search::commands::reveal_in_finder,
            crate::extensions::search::commands::search_apps,
            crate::extensions::search::commands::search_files,
            crate::extensions::system_status::system_snapshot,
            crate::extensions::system_status::system_static_info,
            crate::extensions::translate::ai_translate::translate_ai,
            crate::extensions::translate::ai_translate::translate_ai_stream,
            crate::extensions::translate::get_selected_text,
            crate::extensions::translate::get_selected_text_cached,
            crate::extensions::translate::youdao::translate_youdao,
            crate::extensions::video::video_cancel,
            crate::extensions::video::video_core_status,
            crate::extensions::video::video_ensure_core,
            crate::extensions::video::video_job_status,
            crate::extensions::video::video_probe,
            crate::extensions::video::video_run,
            crate::extensions::window_manager::hide_snap_panel,
            crate::extensions::window_manager::set_frontmost_window_layout,
            crate::extensions::window_manager::set_snap_size,
            crate::extensions::window_manager::set_window_manager_enabled,
            crate::extensions::window_manager::show_snap_panel,
            crate::extensions::zsh_autosuggestions::set_zsh_autosuggestions_enabled,
        ])
    };
}
pub(crate) use configure_app;

/// 将全部 native 扩展注册进 registry（与 native 扫描同源，禁止手写清单）。
pub fn register_all(
    reg: crate::runtime::registry::ExtensionRegistry,
) -> crate::runtime::registry::ExtensionRegistry {
    reg.register(agent::AgentExtension)
        .register(ai_providers::AiProvidersExtension)
        .register(awake::AwakeExtension)
        .register(clean_mode::CleanModeExtension)
        .register(clipboard::ClipboardExtension)
        .register(finder_ext::FinderExtExtension)
        .register(homebrew::HomebrewExtension)
        .register(image::ImageExtension)
        .register(proxy::ProxyExtension)
        .register(screenshot::ScreenshotExtension)
        .register(search::SearchExtension)
        .register(system_status::SystemStatusExtension)
        .register(translate::TranslateExtension)
        .register(video::VideoExtension)
        .register(window_manager::WindowManagerExtension)
        .register(zsh_autosuggestions::ZshAutosuggestionsExtension)
}

#[path = "../../extensions/agent/native/mod.rs"]
pub mod agent;

#[path = "../../extensions/ai-providers/native/mod.rs"]
pub mod ai_providers;

#[path = "../../extensions/awake/native/mod.rs"]
pub mod awake;

#[path = "../../extensions/clean-mode/native/mod.rs"]
pub mod clean_mode;

#[path = "../../extensions/clipboard/native/mod.rs"]
pub mod clipboard;

#[path = "../../extensions/finder-ext/native/mod.rs"]
pub mod finder_ext;

#[path = "../../extensions/homebrew/native/mod.rs"]
pub mod homebrew;

#[path = "../../extensions/image/native/mod.rs"]
pub mod image;

#[path = "../../extensions/proxy/native/mod.rs"]
pub mod proxy;

#[path = "../../extensions/screenshot/native/mod.rs"]
pub mod screenshot;

#[path = "../../extensions/search/native/mod.rs"]
pub mod search;

#[path = "../../extensions/system-status/native/mod.rs"]
pub mod system_status;

#[path = "../../extensions/translate/native/mod.rs"]
pub mod translate;

#[path = "../../extensions/video/native/mod.rs"]
pub mod video;

#[path = "../../extensions/window-manager/native/mod.rs"]
pub mod window_manager;

#[path = "../../extensions/zsh-autosuggestions/native/mod.rs"]
pub mod zsh_autosuggestions;
