// AUTO-GENERATED by scripts/sync-extensions.ts. DO NOT EDIT.
// 仅含扩展 .plugin() 链 + mod 声明；零 generate_handler!（见 §2.8）。

macro_rules! configure_app {
    ($builder:expr) => {
        $builder
        .plugin(crate::extensions::agent::init())
        .plugin(crate::extensions::awake::init())
        .plugin(crate::extensions::clipboard::init())
        .plugin(crate::extensions::finder_ext::init())
        .plugin(crate::extensions::screenshot::init())
        .plugin(crate::extensions::search::init())
        .plugin(crate::extensions::translate::init())
        .plugin(crate::extensions::window_manager::init())
        .plugin(crate::extensions::zsh_autosuggestions::init())
    };
}
pub(crate) use configure_app;

#[path = "../../extensions/agent/native/mod.rs"]
pub mod agent;

#[path = "../../extensions/awake/native/mod.rs"]
pub mod awake;

#[path = "../../extensions/clipboard/native/mod.rs"]
pub mod clipboard;

#[path = "../../extensions/finder-ext/native/mod.rs"]
pub mod finder_ext;

#[path = "../../extensions/screenshot/native/mod.rs"]
pub mod screenshot;

#[path = "../../extensions/search/native/mod.rs"]
pub mod search;

#[path = "../../extensions/translate/native/mod.rs"]
pub mod translate;

#[path = "../../extensions/window-manager/native/mod.rs"]
pub mod window_manager;

#[path = "../../extensions/zsh-autosuggestions/native/mod.rs"]
pub mod zsh_autosuggestions;
