// Auto-generated by scripts/sync-extensions.ts
// Do not edit manually.

// 此模块仅在 specta feature 启用时编译。
// 运行方式：cargo test --features specta export_bindings -- --nocapture
#![cfg(feature = "specta")]

use specta_typescript::Typescript;
use tauri_specta::{collect_commands, Builder, ErrorHandlingMode};

/// 生成 TypeScript bindings 并写入 src/bindings.ts。
#[test]
pub fn export_bindings() {
    let builder = Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            crate::core::shortcut::is_app_active,
            crate::core::shortcut::get_selected_text_cached,
            crate::extensions::screenshot::ocr::ocr_image,
            crate::extensions::screenshot::ocr::detect_text_regions,
            crate::extensions::translate::get_selected_text,
            crate::extensions::translate::ai_translate::translate_ai,
            crate::extensions::translate::youdao::translate_youdao,
            crate::extensions::window_manager::get_screen_info,
            crate::extensions::search::commands::search_apps,
            crate::extensions::search::commands::search_files,
            crate::extensions::search::commands::score_items,
            crate::extensions::ip::fetch_ip_info,
            crate::extensions::clipboard::get_clipboard_history,
            crate::extensions::clipboard::delete_clipboard_items,
            crate::extensions::clipboard::toggle_clipboard_favorite,
            crate::extensions::clipboard::get_clipboard_image,
            crate::extensions::clipboard::paste_clipboard_item,
            crate::extensions::clipboard::paste_clipboard_items,
        ]);

    let out_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts");

    builder
        .export(Typescript::default(), &out_path)
        .expect("生成 TypeScript bindings 失败");

    println!(
        "✅ bindings 已生成：{}",
        out_path.canonicalize().unwrap().display()
    );
}
