// Auto-generated by scripts/sync-extensions.ts
// Do not edit manually.

// 此模块仅在 specta feature 启用时编译。
// 运行方式：cargo test --features specta export_bindings -- --nocapture
#![cfg(feature = "specta")]

use specta_typescript::Typescript;
use tauri_specta::{collect_commands, Builder, ErrorHandlingMode};

/// 生成 TypeScript bindings 并写入 src/bindings.ts。
#[test]
pub fn export_bindings() {
    let builder = Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            crate::core::shortcut::is_app_active,
            crate::core::shortcut::get_selected_text_cached,
            crate::extensions::screenshot::ocr_image,
            crate::extensions::translate::get_selected_text,
            crate::extensions::translate::translate_youdao,
            crate::extensions::translate::translate_ai,
            crate::extensions::search::search_apps,
            crate::extensions::search::search_files,
            crate::extensions::search::score_items,
            crate::extensions::ip::fetch_ip_info,
            crate::extensions::clipboard::get_clipboard_history,
        ]);

    let out_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts");

    builder
        .export(Typescript::default(), &out_path)
        .expect("生成 TypeScript bindings 失败");

    println!(
        "✅ bindings 已生成：{}",
        out_path.canonicalize().unwrap().display()
    );
}
