// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	isAppActive: () => __TAURI_INVOKE<boolean>("is_app_active"),
	getSelectedTextCached: () => __TAURI_INVOKE<string>("get_selected_text_cached"),
	ocrImage: (selX: number | null, selY: number | null, selW: number | null, selH: number | null, scale: number | null, annotationPng: string) => __TAURI_INVOKE<string>("ocr_image", { selX, selY, selW, selH, scale, annotationPng }),
	detectTextRegions: (scale: number | null) => __TAURI_INVOKE<TextRegion[]>("detect_text_regions", { scale }),
	getSelectedText: () => __TAURI_INVOKE<string>("get_selected_text"),
	translateAi: (text: string, endpoint: string, apiKey: string, model: string, targetLang: string | null, prompt: string | null) => __TAURI_INVOKE<TranslateResult>("translate_ai", { text, endpoint, apiKey, model, targetLang, prompt }),
	translateYoudao: (text: string, appKey: string, appSecret: string, targetLang: string | null) => __TAURI_INVOKE<TranslateResult>("translate_youdao", { text, appKey, appSecret, targetLang }),
	searchApps: (query: string) => __TAURI_INVOKE<SearchResult[]>("search_apps", { query }),
	searchFiles: (query: string) => __TAURI_INVOKE<SearchResult[]>("search_files", { query }),
	scoreItems: (query: string, items: string[]) => __TAURI_INVOKE<number[]>("score_items", { query, items }),
	fetchIpInfo: (ip: string | null) => __TAURI_INVOKE<IpInfo>("fetch_ip_info", { ip }),
	getClipboardHistory: (query: string | null, filterFavorite: boolean | null, limit: number | null, previewOnly: boolean | null) => __TAURI_INVOKE<ClipboardItem[]>("get_clipboard_history", { query, filterFavorite, limit, previewOnly }),
	deleteClipboardItems: (ids: string[]) => __TAURI_INVOKE<null>("delete_clipboard_items", { ids }),
	getClipboardImage: (id: string) => __TAURI_INVOKE<string | null>("get_clipboard_image", { id }),
	pasteClipboardItem: (id: string) => __TAURI_INVOKE<null>("paste_clipboard_item", { id }),
	pasteClipboardItems: (ids: string[]) => __TAURI_INVOKE<null>("paste_clipboard_items", { ids }),
	toggleClipboardFavorite: (id: string) => __TAURI_INVOKE<null>("toggle_clipboard_favorite", { id }),
};

/* Types */
export type ClipboardItem = {
	id: string,
	content: string,
	content_type: string,
	source_app: string,
	created_at: string,
	is_favorite: boolean,
	score: number,
	file_size: number | null,
	image_width: number | null,
	image_height: number | null,
};

export type IpInfo = {
	ip: string | null,
	success: boolean | null,
	message: string | null,
	country: string | null,
	region: string | null,
	city: string | null,
	isp: string | null,
	org: string | null,
	asn: string | null,
};

export type SearchResult = {
	id: string,
	title: string,
	path: string,
	kind: string,
	icon: string | null,
	last_used: string | null,
	score: number | null,
};

export type TextRegion = {
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
};

export type TranslateResult = {
	source: string,
	translation: string,
	engine: string,
};

