// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	isAppActive: () => __TAURI_INVOKE<boolean>("is_app_active"),
	getSelectedTextCached: () => __TAURI_INVOKE<string>("get_selected_text_cached"),
	ocrImage: (selX: number | null, selY: number | null, selW: number | null, selH: number | null, scale: number | null, annotationPng: string) => __TAURI_INVOKE<OcrResult>("ocr_image", { selX, selY, selW, selH, scale, annotationPng }),
	detectTextRegions: (scale: number | null) => __TAURI_INVOKE<TextRegion[]>("detect_text_regions", { scale }),
	getSelectedText: () => __TAURI_INVOKE<string>("get_selected_text"),
	translateAi: (text: string, endpoint: string, apiKey: string, model: string, targetLang: string | null, prompt: string | null) => __TAURI_INVOKE<TranslateResult>("translate_ai", { text, endpoint, apiKey, model, targetLang, prompt }),
	translateYoudao: (text: string, appKey: string, appSecret: string, targetLang: string | null) => __TAURI_INVOKE<TranslateResult>("translate_youdao", { text, appKey, appSecret, targetLang }),
	getScreenInfo: () => __TAURI_INVOKE<ScreenInfo[]>("get_screen_info"),
	setFrontmostWindowLayout: (layout: string, customWidth: number | null, customHeight: number | null, prevPid: number | null) => __TAURI_INVOKE<null>("set_frontmost_window_layout", { layout, customWidth, customHeight, prevPid }),
	checkWindowManagerAccessibility: () => __TAURI_INVOKE<boolean>("check_window_manager_accessibility"),
	toggleDragSnap: (enabled: boolean, customWidth: number | null, customHeight: number | null) => __TAURI_INVOKE<null>("toggle_drag_snap", { enabled, customWidth, customHeight }),
	isDragSnapActive: () => __TAURI_INVOKE<boolean>("is_drag_snap_active"),
	showSnapPanel: () => __TAURI_INVOKE<null>("show_snap_panel"),
	hideSnapPanel: () => __TAURI_INVOKE<null>("hide_snap_panel"),
	/**  返回全量应用列表（带 use_count + last_used），由前端做拼音匹配与排序。 */
	searchApps: () => __TAURI_INVOKE<SearchResult[]>("search_apps"),
	/**
	 *  用 mdfind 拉候选，通过 kMDItemContentType 判断文件/文件夹类型，
	 *  返回带元数据的原始列表，由前端打分排序。
	 */
	searchFiles: (query: string) => __TAURI_INVOKE<SearchResult[]>("search_files", { query }),
	fetchIpInfo: (ip: string | null) => __TAURI_INVOKE<IpInfo>("fetch_ip_info", { ip }),
	getClipboardHistory: (filterFavorite: boolean | null, limit: number | null, previewOnly: boolean | null) => __TAURI_INVOKE<ClipboardItem[]>("get_clipboard_history", { filterFavorite, limit, previewOnly }),
	deleteClipboardItems: (ids: string[]) => __TAURI_INVOKE<null>("delete_clipboard_items", { ids }),
	toggleClipboardFavorite: (id: string) => __TAURI_INVOKE<null>("toggle_clipboard_favorite", { id }),
	getClipboardImage: (id: string) => __TAURI_INVOKE<string | null>("get_clipboard_image", { id }),
	pasteClipboardItem: (id: string) => __TAURI_INVOKE<null>("paste_clipboard_item", { id }),
	pasteClipboardItems: (ids: string[]) => __TAURI_INVOKE<null>("paste_clipboard_items", { ids }),
};

/* Types */
export type ClipboardItem = {
	id: string,
	content: string,
	content_type: string,
	source_app: string,
	created_at: string,
	is_favorite: boolean,
	score: number,
	file_size: number | null,
	image_width: number | null,
	image_height: number | null,
};

export type IpInfo = {
	ip: string | null,
	success: boolean | null,
	message: string | null,
	country: string | null,
	region: string | null,
	city: string | null,
	isp: string | null,
	org: string | null,
	asn: string | null,
};

export type OcrResult = {
	text: string,
	qr: string[],
};

export type ScreenInfo = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	is_main: boolean,
};

export type SearchResult = {
	id: string,
	title: string,
	path: string,
	kind: string,
	icon: string | null,
	last_used: string | null,
	score: number | null,
	/**  累计使用次数（mdfind kMDItemUseCount + 会话内增量），供前端打分加权。 */
	use_count: number | null,
	/**  文件父目录名（仅文件结果），供前端补充匹配字段。 */
	parent: string | null,
};

export type TextRegion = {
	x: number | null,
	y: number | null,
	w: number | null,
	h: number | null,
};

export type TranslateResult = {
	source: string,
	translation: string,
	engine: string,
};

